---
- hosts: websever
  tasks:
    - name: login to jfrog
      shell: docker login -u devops6789@gmail.com -p Siddu@9880 shstechacademy.jfrog.io     
    
    - name: pull an image
      shell: docker pull shstechacademy.jfrog.io/sampledockeruplaod/newimage:31

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 shstechacademy.jfrog.io/sampledockeruplaod/newimage:31
 
   
